### ISSUE TITLE
Getting a GPU device

### ISSUE THREAD

**Issue by eleon** [hpc/quo-vadis#1]
We need a function to retrieve a GPU (and other devices) from a given scope, for example: 
```C
QV_scope_get_device(in:qv-context, in:scope, in:QV_RES_GPU, in:i, in:type, out:device);
```
Retrieve the `i`th GPU from the input `scope`. 
The output `device` is a string of one of the following `type`s:
* UUID
* PCI Bus ID
* Ordinal ID 

A user can retrieve a GPU from its PCI Bus ID, for example, using the following call: 
```
(cuda/hip)DeviceGetByPCIBusId( int* device, const char* pciBusId)
(cuda/hip)SetDevice(int device)
```
 An example can be found here: 
https://github.com/LLNL/mpibind/blob/master/gpu-tests/retrieve.cu

To get the different IDs (UUID, PCI Bus ID, etc.) of a device using hwloc, see the function `discover_devices` here:
https://github.com/LLNL/mpibind/blob/master/src/internals.c

**Comment by samuelkgutierrez** [comment]
This functionality should now be complete. Please re-open if this is not the case.

**Comment by eleon** [comment]
Nice work, @samuelkgutierrez. I tried it on a system with NVIDIA GPUs and it works well.
