### ISSUE TITLE
Context create functions

### ISSUE THREAD

**Issue by eleon** [hpc/quo-vadis#11]
Currently, we have `qv_mpi_create` to create a QV context associated with an MPI communicator. We may need additional functions for non-MPI cases where, for example, only POSIX threads will be used. A naming option is the following: 
```
qv_ctx_create_pthread
qv_ctx_create_mpi
qv_ctx_create_argobots
```

**Comment by eleon** [comment]
A user wouldn't be able to call `qvi_context_create` directly, correct (`i` for internal)? Thus, we would need something like `qv_pthread_context_create()`?

**Comment by samuelkgutierrez** [comment]
Yes, that's correct.
