### ISSUE TITLE
Delete Old Thread Interface?

### ISSUE THREAD

**Issue by samuelkgutierrez** [hpc/quo-vadis#182]
Since we are moving to a new thread interface, can we delete the code associated with the old interface? This would simplify things, in my opinion. @GuillaumeMercier and @eleon what do you think?

**Comment by GuillaumeMercier** [comment]
Sounds sensible. Do you want me to take care of it or do you want to go ahead and do it yourself?

**Comment by samuelkgutierrez** [comment]
Can you please do that? I don't want to mess that up. Thank you, @GuillaumeMercier.

**Comment by GuillaumeMercier** [comment]
Will do (probably not today though).
