### ISSUE TITLE
Restricting GPU topology

### ISSUE THREAD

**Issue by eleon** [hpc/quo-vadis#2]
We need a way to restrict a given topology not only on CPUs but also on GPUs. This may be tricky because there is no direct support for this in hwloc directly. 

One approach is to use the VISIBLE_DEVICES environment variables, but we may need to use `fork()` or similar heavy-weight functions: 
https://github.com/ROCm-Developer-Tools/HIP/blob/main/tests/src/runtimeApi/device/hipSetGetDevice.cpp

Another approach may be using CUDA- or ROCM-related functions in hwloc, but I am not sure these functions provide what we need.

**Comment by samuelkgutierrez** [comment]
@eleon does the functionality that we in 2703e8810c0ba510467b397e50c8a7aaa39f7004 meet this need? It appears to provide what is required, but maybe I'm missing a subtlety.

**Comment by samuelkgutierrez** [comment]
> @eleon does the functionality that we in [2703e88](https://github.com/hpc/quo-vadis/commit/2703e8810c0ba510467b397e50c8a7aaa39f7004) meet this need? It appears to provide what is required, but maybe I'm missing a subtlety.

This question isn't clear. What I meant to ask is: does the current behavior in `master` meet the GPU restriction requirements?

**Comment by eleon** [comment]
@samuelkgutierrez , yes, I believe the `split` and `split_at` functions help restricting/assigning GPUs. I think this should be enough for now. The `get_topology` function outlined above could be helpful for those algorithms that take an hwloc topology (rather than a `scope`) as input, e.g., `mpibind`, but we don't have an immediate need to support this.
