### ISSUE TITLE
Build system tweaks

### ISSUE THREAD

**Issue by GuillaumeMercier** [hpc/quo-vadis#22]
1. It may be interesting to consider using the version of hwloc installed on the target system rather than compiling our own version.
2. libpciaccess is required even though the support for GPU is not activated
3. the whole dependency on libpciaccess can be dropped because hwloc does not  really need it (quoting the main hwloc developer)

**Comment by samuelkgutierrez** [comment]
@GuillaumeMercier, 0ee2e85513f3691c1f114f5df7fd5e240474cb47 address points 2 and 3.

**Comment by samuelkgutierrez** [comment]
To point 1: version compatibility is challenging enough that we'll stick to our internal version until there is a compelling reason to also support system-installed hwloc libraries.
