### ISSUE TITLE
Building hwloc with device support

### ISSUE THREAD

**Issue by eleon** [hpc/quo-vadis#3]
To manage devices such as GPUs, we may need to build hwloc with the appropriate device drivers: 
* CUDA
    * `CPPFLAGS+=-I$cuda_root/include`
    * `LDFLAGS+=-L$cuda_root/lib64`
* ROCm
    * `CPPFLAGS+=-I$rocm_root/rocm_smi/include`
    * `CPPFLAGS+=-I$rocm_root/opencl/include`
    * `LDFLAGS+=-L$rocm_root/lib`
   
Then, build hwloc with `--enable-plugins=rsmi,cuda,nvml`

We would need to check if CUDA and ROCm are installed in the system and, if so, add the appropriate flags.

**Comment by samuelkgutierrez** [comment]
Looks like this is done.
