### ISSUE TITLE
Add Build Option to Specify Underlying MPI Process Type

### ISSUE THREAD

**Issue by samuelkgutierrez** [hpc/quo-vadis#33]
Consider adding a build option that allows for building against thread-based MPI implementations and automatically setting the correct task type in `qvi_mpi_init()` (e.g., `QV_TASK_TYPE_THREAD`).

@GuillaumeMercier may be interested in this, so I will tag him.

**Comment by GuillaumeMercier** [comment]
@samuelkgutierrez : yes, I've been thinking about something like this but I'm not CMake fluent enough to achieve this in a reasonable amount of time. But to me, it's the best way to go actually.

**Comment by samuelkgutierrez** [comment]
@GuillaumeMercier I pushed something rudimentary. Please update as you see fit.

**Comment by GuillaumeMercier** [comment]
@samuelkgutierrez : it's nice, and it gives a template for future CMake modifications to introduce more configure-time options
when/if needed. Thanks.
