### ISSUE TITLE
Cross-Paradigm Scope Acquisition

### ISSUE THREAD

**Issue by samuelkgutierrez** [hpc/quo-vadis#35]
We probably need a cross-paradigm scope acquisition function. For example, threads acquiring and then operating on a scope created from within an MPI context. In this use case, the idea is that the threads want to operate within the hardware bounds defined by the scope created by the parent MPI process.

Input is welcome.

**Comment by GuillaumeMercier** [comment]
That is a good point. From the top of my head, I would see a shared/sharable attribute (because this might incur an overhead) + a function to give/inherit said scope. Depending on how far I get, I may be able to draft an example that could point out the needs in this regard.

**Comment by samuelkgutierrez** [comment]
The way I see it is that there are two major sharing modes:
* Intra-task (e.g., thread to process, process to thread, process to process). Internally this case seems straightforward to implement: initialize a new group in the target context and acquire the source scope's hardware pool.
* Inter-task (e.g., MPI processes to some other distributed middleware). We don't have this use-case yet since MPI is the only distributed middleware we support, but it's worth thinking about. In this case, we'll have to implement something that looks like distributed intra-task sharing (which shouldn't be a big deal).

**Comment by samuelkgutierrez** [comment]
I believe this issue is addressed with the new methodologies we are using now.
