### ISSUE TITLE
Missing `finalize` function for zgroups?

### ISSUE THREAD

**Issue by GuillaumeMercier** [hpc/quo-vadis#39]
zgroups seems to have an `initialize` routine, but not a `finalize` one.
In the case of the thread version of this, a `pthread_barrier_destroy` is done in the finalize, thus never called.
Is this normal?

**Comment by samuelkgutierrez** [comment]
Could you accomplish `pthread_barrier_destroy` in the zgroup-thread destructor?

**Comment by GuillaumeMercier** [comment]
Yes, but it doesn't seem logical to me.

**Comment by samuelkgutierrez** [comment]
Looking into this a little closer: `initialize()` is not a required virtual interface, so this asymmetry is only a peculiarity of the deriving classes. If you want a matching `finalize()` in `qvi-zgroup-thread`, please add it since it doesn't affect other zgroups.
