### ISSUE TITLE
Support for hybrid MPI + OpenMP programs

### ISSUE THREAD

**Issue by GuillaumeMercier** [hpc/quo-vadis#41]
I think something is either missing or should be modified in the current interface to support such programs.
Let us take the folliowing situation :

```
MPI_Init(NULL, NULL);

 qv_context_t *mpi_ctx;
 qv_mpi_context_create(&mpi_ctx, MPI_COMM_WORLD);
 
qv_scope_t *mpi_scope;
qv_scope_get( mpi_ctx, QV_SCOPE_JOB, &mpi_scope);

qv_scope_t *mpi_numa_scope;
// suppose rank and #numa are known 
qv_scope_split_at(mpi_ctx, mpi_scope,  QV_HW_OBJ_NUMANODE, mpi_rank % number_of _numa,  &mpi_numa_scope);

int my_numa_id
qv_scope_taskid(mpi_ctx, mpi_numa_scope, &my_numa_id);

// Master spawns parallel section, let us suppose one thread per PU
if (my_numa_id == 0) {
#pragma omp parallel 
    {
          qv_context_t *omp_ctx;
          qv_thread_context_create(&omp_ctx);

          qv_scope_t *omp_self_scope;
          qv_scope_get(
              omp_ctx,
              QV_SCOPE_PROCESS, // ONLY INTRINSIC SCOPES SUPPORTED
              &omp_self_scope
          );
 
      /* do  stuff  here */

    }  
 }
```
How can my `omp_self_scope` be derived from my previous `mpi_numa_scope` ?
Currently it's not possible, as I have to provide an instrinsic in  `qv_scope_get`.

My example is running but the number of resources reported is not the right one since this OpenMP context is not related 
to the previous MPI one.

Should we allow regular scopes to be taken as arguments to  `qv_scope_get`?
Or am I missing something?

**Comment by samuelkgutierrez** [comment]
This is a great question and you are correct! This issue is related to Issue #35. 

Allowing arbitrary scopes in `qv_scope_get()` could be a viable solution, but we should discuss this.

**Comment by GuillaumeMercier** [comment]
Ah yes. I did not correctly understood what you meant then. 
Now that I'm trying to actually write an hybrid program, the issue jumps in my face.

**Comment by GuillaumeMercier** [comment]
> Allowing arbitrary scopes in `qv_scope_get()` could be a viable solution, but we should discuss this.

Definitely!  I'm reluctant to add yet another function for this:  a simple example  already uses a lot of calls to the QV interface.
Therefore, using arbitrary scopes could be a way to go but I have to give more thought to this, as there are probaly issues
that I can't see for thee moment.

**Comment by GuillaumeMercier** [comment]
BTW, I think that the intrinsic scope `QV_SCOPE_PROCESS` is quite misleading in my example because OpenMP considers threads and QV treats this silently internally by replacing pids with tids for requests to the server. Should we make this difference explicit? I mean that a thead might want to get the scope for its whole process (not just itself) and right now it's not possible.
I think that introducing a  `QV_SCOPE_THREAD` could do the trick.

**Comment by samuelkgutierrez** [comment]
> BTW, I think that the intrinsic scope `QV_SCOPE_PROCESS` is quite misleading in my example because OpenMP considers threads and QV treats this silently internally by replacing pids with tids for requests to the server. Should we make this difference explicit? I mean that a thead might want to get the scope for its whole process (not just itself) and right now it's not possible. I think that introducing a `QV_SCOPE_THREAD` could do the trick.

Could you please open another issue to track this? I need to think about this a little more. Maybe we can replace `PROCESS` and `THREAD` with `SELF` and deduce the appropriate type from the calling context?

**Comment by samuelkgutierrez** [comment]
Today we discussed how to simplify fine-grained threading support in a hybrid setting. A proposal was made to consider adopting a HIPPO-like approach with a thread-specific call that might look something like:

```
int
qv_thread_layout_bind(
    qv_context_t *ctx,
    qv_scope_t *parent,
    qv_thread_layout_t layout
);
```

The idea is that this interface could greatly simplify fine-grained thread binding policies and also potentially eliminate the complications dealing with cross-paradigm scope acquisition (at least in this case).

**Comment by samuelkgutierrez** [comment]
I'm going to close this issue since @GuillaumeMercier has implemented the HIPPO-like approach discussed earlier.
