### ISSUE TITLE
Group table management in `qvi_thread_t` is problematic

### ISSUE THREAD

**Issue by GuillaumeMercier** [hpc/quo-vadis#44]
Currently only one thread in an OpenMP team is making the `insert` call (and also determining the group id)
since several threads are part of the group.
However, the id used is the one from the thread making the insertion.
If a thread gets the group and queries the id, it's going to be the id of the thread that made the insertion
in the group table and not it's own.
This should be fixed.

**Comment by samuelkgutierrez** [comment]
@GuillaumeMercier #176 should help with this. Let's discuss how we can handle this now inside the threaded code.

**Comment by samuelkgutierrez** [comment]
This is a stale issue because of how threading in handled now.
