### ISSUE TITLE
Fortran compiler not detected

### ISSUE THREAD

**Issue by GuillaumeMercier** [hpc/quo-vadis#58]
On my system, the Fortran compiler (gfortan) is not detected and I have to manually modify the CMakeCache.txt file
(the `CMAKE_Fortran_COMPILER` variable).
Error message is the following:
```
-- Determining desired Fortran support level
-- Determining desired Fortran support level - enabled
-- The Fortran compiler identification is unknown
CMake Error at cmake/QVFortranSupport.cmake:21 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:40 (include)
```

**Comment by samuelkgutierrez** [comment]
`gfortran` support on my systems works reliably. I wonder what's different on your system? Is it in your `$PATH`?

**Comment by samuelkgutierrez** [comment]
Does setting `FC` to the `gfortran` path before your `cmake` invocation work? For example `FC=/foo/bar/gfortran cmake ..`.

**Comment by samuelkgutierrez** [comment]
Another question: maybe we should make Fortran support optional. That is, if you don't disable it and it isn't found, just continue along? I think I like this behavior. I thought we already had that, but maybe not. I can fix that.

**Comment by samuelkgutierrez** [comment]
@GuillaumeMercier please let me know if 86ec3a6 addresses your issue. Nice catch, by the way!

**Comment by GuillaumeMercier** [comment]
@samuelkgutierrez

> @GuillaumeMercier please let me know if [86ec3a6](https://github.com/hpc/quo-vadis/commit/86ec3a66189a80378580f7d146b9302108a31758) addresses your issue. Nice catch, by the way!

It does indeed. And gfortran was in my `PATH` by the way. Thanks!

**Comment by samuelkgutierrez** [comment]
Nice! It would be nice to understand why Fortran autodetect isn't working on your system. Can you please find the relevant output in `build/CMakeFiles/CMakeOutput.log` and see if you can find clues about what is going wrong? Thank you.

**Comment by GuillaumeMercier** [comment]
I'm not getting it. Your latest commit fixed the issue. Do you want me to revert it and see what was goind wrong?

**Comment by samuelkgutierrez** [comment]
Haha! No, I'm fine with it working---even if accidentally.
