### ISSUE TITLE
Merge qv_scope_th_split_at() and qv_scope_split_at()

### ISSUE THREAD

**Issue by samuelkgutierrez** [hpc/quo-vadis#68]

**Comment by eleon** [comment]
Original split operation:
```
int
qv_scope_split_at(
    qv_context_t *ctx,
    qv_scope_t *scope,
    qv_hw_obj_type_t type,
    int group_id,
    qv_scope_t **subscope
);
```

Generalized split operation:
```
int
qv_scope_split_at(
    qv_context_t *ctx,
    qv_scope_t *scope,
    qv_hw_obj_type_t type,
    int *group_id,
    int nthreads, 
    qv_scope_t ***subscope
);
```

Differences:
* `group_id` (in) is an array of ids of size `nthreads`. It can take the value of `NULL` to assign a default color. 
* `nthreads` (in) is the number of threads in this process. It is used to differentiate between splitting resources among processes (`nthreads=1`) and splitting resources among threads (`nthreads>1`).
* `subscope` (out) is an array of scope pointers of size `nthreads`

We could also add another parameter `int policy` (enumeration). When `policy != QV_SPLIT_USE_GROUP_ID`, ignore `group_id` and use any of the predefined policies such as `QV_SPLIT_AUTO`, `QV_SPLIT_COMPACT`, or `QV_SPLIT_STRIDE_2`. We could leave this for later and only if it seems necessary. 


Splitting resources among processes/tasks:
```
// Split resources by NUMA domains among Tasks 

qv_scope_nobjs(ctx, scope, QV_HW_OBJ_NUMA, &nnumas);

int nthreads = 1; 
int group_id = rank % nnumas; 
qv_scope_t **task_scope;

qv_scope_split_at(ctx, scope, QV_HW_OBJ_NUMA,
    &group_id,
    nthreads,
    &task_scope);

qv_scope_t *numa_scope = task_scope[0];

/* Do work in this NUMA domain */ 

/* Done using numa_scope */
free(numa_scope);
free(task_scope); 
```

Splitting resource among threads:
```
// Split an existing NUMA scope by Cores among Threads

qv_scope_nobjs(ctx, numa_scope, QV_HW_OBJ_CORE, &ncores);

int nthreads = ncores; 
int *th_group_id = NULL;   // Use default value 
qv_scope_t **th_scope; 

qv_scope_split_at(ctx, numa_scope, QV_HW_OBJ_CORE,
    th_group_id,
    nthreads, 
    &th_scope);

omp_set_num_threads(nthreads);
#pragma omp parallel
{
  qv_bind_push(ctx, th_scope[omp_get_thread_num()]);

  /* Each thread works */
}

/* Done with all parallel regions using this layout */ 
for (i=0; i<nthreads; i++)
  free(th_scope[i]);
free(th_scope);
```

**Comment by samuelkgutierrez** [comment]
Consider using the `group_id` array to pass pre-defined mapping policies to avoid having another parameter.

**Comment by samuelkgutierrez** [comment]
Discussed. Will not merge interfaces.
