### ISSUE TITLE
Merge qv_scope_th_split() and qv_scope_split()

### ISSUE THREAD

**Issue by samuelkgutierrez** [hpc/quo-vadis#69]

**Comment by eleon** [comment]
Generalization of this operation very similar to #68 

Original split operation:
```
int
qv_scope_split(
    qv_context_t *ctx,
    qv_scope_t *scope,
    int npieces,
    int group_id,
    qv_scope_t **subscope
);
```

Generalized split operation:
```
int
qv_scope_split(
    qv_context_t *ctx,
    qv_scope_t *scope,
    int npieces, 
    int *group_id,
    int nthreads, 
    qv_scope_t ***subscope
);
```

Differences:
* `group_id` (in) is an array of ids of size `nthreads`. It can take the value of `NULL` to assign a default group_id/color. 
* `nthreads` (in) is the number of threads in this process. It is used to differentiate between splitting resources among processes (`nthreads=1`) and splitting resources among threads (`nthreads>1`).
* `subscope` (out) is an array of scope pointers of size `nthreads`

We could also add another parameter `int policy` (enumeration). When `policy != QV_SPLIT_USE_GROUP_ID`, ignore `group_id` and use any of the predefined policies such as `QV_SPLIT_AUTO`, `QV_SPLIT_COMPACT`, or `QV_SPLIT_STRIDE_2`. Let's leave this for later and only if it seems necessary. 

We could leverage C++ and make `nthreads` optional. If `nthreads` is passed in, then parameter types are: `int group_id` and `qv_scope_t **subscope`, i.e., the original paramter types. In this case, however, users would have to be careful about passing the right parameter type, which may be error prone and more complex than just having the `nthreads` parameter all the time--consistency!

Splitting resources among processes/tasks:
```
// Split resources of an existing scope among Tasks 

int nthreads = 1; 
int group_id = rank % node_local_ntasks;  
qv_scope_t **task_scope;

qv_scope_split(ctx, scope, node_local_ntasks,
    &group_id,
    nthreads,
    &task_scope);

qv_scope_t *sub_scope = task_scope[0];

/* Task does work in this scope */ 

/* Done using sub_scope */
free(sub_scope);
free(task_scope); 
```

Splitting resources among threads:
```
// Split an existing NUMA scope among N Threads

int nthreads = N; 
int *th_group_id = NULL;   // Use group_id default value 
qv_scope_t **th_scope; 

qv_scope_split(ctx, numa_scope, N,
    th_group_id,
    nthreads, 
    &th_scope);

omp_set_num_threads(nthreads);
#pragma omp parallel
{
  qv_bind_push(ctx, th_scope[omp_get_thread_num()]);

  /* Each thread works */
}

/* Done with all parallel regions using this layout */ 
for (i=0; i<nthreads; i++)
  free(th_scope[i]);
free(th_scope);
```

**Comment by samuelkgutierrez** [comment]
Consider using the `group_id` array to pass pre-defined mapping policies to avoid having another parameter.

**Comment by samuelkgutierrez** [comment]
Hello. The more I work on and think about this, the more I'm convinced that we should keep `qv_scope_split()` and discuss what we should do with the thread split interface. Let's discuss this next week.

**Comment by samuelkgutierrez** [comment]
Discussed. Will not merge interfaces.
