### ISSUE TITLE
Getting devices in subscopes

### ISSUE THREAD

**Issue by eleon** [hpc/quo-vadis#8]
Getting the number of GPUs from the base/initial scope works fine, but if the scope is split the resulting scopes do not have any of the GPUs. This issue can be reproduced with the following test: 
https://github.com/hpc/quo-vadis/blob/master/tests/test-mpi-getdev.c

**Comment by samuelkgutierrez** [comment]
@eleon please take a look at 76ec280a16573525668628251e2c7c02f7c2e9d4. This issue is almost resolved. Please look at commit for further details.

**Comment by samuelkgutierrez** [comment]
The work on `qvi_scope_get_device()` is complete. This feature is ready for broader testing. Testing on my end looks good. Please see c098b0e9c1652338926dddd481f517c1f9e939ee for more details.

**Comment by eleon** [comment]
Nice work, @samuelkgutierrez . I tested on `corona` and the issue seems resolved.
